CREATE TABLE projects (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE,
	spec_json TEXT NOT NULL,
	remark TEXT NOT NULL,
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE videos (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	project_id INTEGER NOT NULL REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
	name TEXT NOT NULL,
	frame_urls TEXT NOT NULL,
	annotation_json TEXT,
	annotation_version TEXT NOT NULL DEFAULT '',
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(project_id, name)
);
