version: "3"

tasks:
  start:
    cmds:
      - go run main.go start
    dir: module/track

  build:
    cmds:
      - CGO_ENABLED=0 go build -o ../../build/nutsh-track -trimpath main.go
    dir: module/track

  run:
    cmds:
      - go run main.go {{.CLI_ARGS}}
    dir: module/track
